# Generated by Django 5.0.3 on 2025-02-12 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_name', models.CharField(max_length=255, verbose_name='Название ранга')),
                ('rank_type', models.CharField(choices=[('customer', 'Заказчик'), ('executor', 'Исполнитель')], max_length=10, verbose_name='Тип ранга')),
                ('rank_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена ранга')),
                ('rank_image_url', models.ImageField(blank=True, null=True, upload_to='rank/photo/%Y/%m/%d/', verbose_name='Фотография')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Ранг',
                'verbose_name_plural': 'Ранги',
            },
        ),
        migrations.CreateModel(
            name='RankDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_text', models.TextField(verbose_name='Описание привилегии')),
                ('privilege_type', models.CharField(choices=[('quantitative', 'Количественный'), ('unique', 'Уникальный')], max_length=15, verbose_name='Тип привилегии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='rank.rank', verbose_name='Ранг')),
            ],
            options={
                'verbose_name': 'Описание ранга',
                'verbose_name_plural': 'Описания рангов',
            },
        ),
        migrations.CreateModel(
            name='RankSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_role', models.CharField(choices=[('executer', 'исполнитель'), ('customer', 'заказчик')], max_length=20, verbose_name='Тип пользователя')),
                ('discount_internal_purchases', models.IntegerField(default=0, verbose_name='Скидка на внутренние покупки (%)')),
                ('referral_bonus_self', models.IntegerField(default=0, verbose_name='Бонус за приглашенного пользователя (₽)')),
                ('referral_bonus_invited', models.IntegerField(default=0, verbose_name='Бонус для приглашенного пользователя (₽)')),
                ('discount_orders', models.IntegerField(default=0, verbose_name='Скидка на заказы (%)')),
                ('commission_reduction', models.IntegerField(default=0, verbose_name='Снижение комиссии от заказа (%)')),
                ('notifications_to_executor', models.BooleanField(default=False, verbose_name='Уведомления исполнителю')),
                ('market_price_stats', models.BooleanField(default=False, verbose_name='Вывод статистики рыночных цен')),
                ('extra_discount_per_order', models.BooleanField(default=False, verbose_name='Дополнительная скидка после каждого заказа')),
                ('visibility_other_universities', models.BooleanField(default=False, verbose_name='Видимость исполнителей из других университетов')),
                ('bonus_to_fiat_transfer', models.BooleanField(default=False, verbose_name='Перевод бонусов в фиат')),
                ('monthly_contests', models.BooleanField(default=False, verbose_name='Участие в ежемесячных конкурсах')),
                ('create_internal_courses', models.BooleanField(default=False, verbose_name='Доступ к созданию внутренних курсов')),
                ('publish_articles', models.BooleanField(default=False, verbose_name='Публикация статей')),
                ('upload_work_to_study', models.BooleanField(default=False, verbose_name='Загрузка успешных работ в справочник StudY')),
                ('mandatory_review', models.BooleanField(default=False, verbose_name='Обязательный отзыв от заказчика')),
                ('unlimited_fiat_withdrawals', models.BooleanField(default=False, verbose_name='Вывод фиатных средств без ограничений')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('rank', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='rank.rank', verbose_name='Ранг')),
            ],
            options={
                'verbose_name': 'Настройки ранга',
                'verbose_name_plural': 'Настройки рангов',
            },
        ),
    ]
