# Generated by Django 5.0.3 on 2025-02-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranksettings',
            name='bonus_account_limit',
            field=models.IntegerField(default=0, verbose_name='Ограничения бонусного счета (₽)'),
        ),
        migrations.AddField(
            model_name='ranksettings',
            name='can_print',
            field=models.BooleanField(default=False, verbose_name='Возможность печатать'),
        ),
        migrations.AddField(
            model_name='ranksettings',
            name='customer_unlimited_fiat_withdrawals',
            field=models.BooleanField(default=False, verbose_name='Снятие с фиатного счета без ограничений'),
        ),
        migrations.AddField(
            model_name='ranksettings',
            name='executer_unlimited_fiat_withdrawals',
            field=models.BooleanField(default=False, verbose_name='Снятие с фиатного счета без ограничений'),
        ),
    ]
