# Generated by Django 5.0.3 on 2025-02-07 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiat_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Фиатный счет')),
                ('frozen_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Замороженный счет')),
                ('bonus_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Бонусный счет')),
                ('forfeited_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Баланс упущенной прибыли')),
            ],
            options={
                'verbose_name': 'Баланс',
                'verbose_name_plural': 'Баланс пользователей',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('transaction_type', models.CharField(choices=[('bonus_add', 'Пополнение бонусов'), ('bonus_transfer', 'Перевод бонусов'), ('deposit', 'Пополнение'), ('withdrawal', 'Вывод'), ('payment', 'Оплата'), ('refund', 'Возврат'), ('freeze', 'Заморозка'), ('unfreeze', 'Разморозка')], max_length=20, verbose_name='Тип транзакции')),
                ('comment', models.CharField(max_length=155, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('pending', 'В обработке'), ('completed', 'Завершено'), ('cancel', 'Отклонено'), ('failed', 'Ошибка')], default='completed', max_length=10, verbose_name='Статус')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('card_number', models.CharField(max_length=255, verbose_name='Номер карты')),
                ('status', models.CharField(choices=[('В обработке', 'В обработке'), ('Завершена', 'Завершена'), ('Отклонена', 'Отклонена')], default='В обработке', max_length=40, verbose_name='Статус заявки')),
                ('date_submitted', models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи заявки')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('date_completed', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Заявка на вывод средств',
                'verbose_name_plural': 'Заявки на вывод средств',
            },
        ),
    ]
