# Generated by Django 5.0.3 on 2025-02-07 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='withdrawalrequest',
            options={'verbose_name': 'Заявка на вывод', 'verbose_name_plural': 'Заявки на вывод'},
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='description',
        ),
        migrations.AddField(
            model_name='transaction',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='Ошибка'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='target_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transactions', to='server.profile', verbose_name='Профиль получателя'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.transaction', verbose_name='Связанная транзакция'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='comment',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='server.profile', verbose_name='Профиль отправителя'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'В обработке'), ('completed', 'Завершено'), ('cancelled', 'Отклонено'), ('failed', 'Ошибка')], default='completed', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('bonus_add', 'Пополнение бонусов'), ('bonus_transfer', 'Перевод бонусов'), ('deposit', 'Пополнение'), ('withdrawal', 'Вывод'), ('payment', 'Оплата'), ('refund', 'Возврат'), ('freeze', 'Заморозка'), ('unfreeze', 'Разморозка'), ('commission', 'Комиссия'), ('adjustment', 'Коррекция')], max_length=20, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='date_submitted',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'В обработке'), ('completed', 'Завершена'), ('cancelled', 'Отклонена')], default='pending', max_length=40, verbose_name='Статус заявки'),
        ),
    ]
