# Generated by Django 5.0.3 on 2025-02-08 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_withdrawalrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'В обработке'), ('completed', 'Завершено'), ('cancel', 'Отклонено'), ('failed', 'Ошибка'), ('frozen', 'Заморожено'), ('waiting_confirmation', 'Ожидание подтверждения'), ('reversed', 'Отменено после обработки'), ('penalized', 'Санкционное списание')], default='completed', max_length=155, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('bonus_add', 'Пополнение бонусов'), ('bonus_transfer', 'Перевод бонусов'), ('deposit', 'Пополнение фиата'), ('withdrawal', 'Вывод фиата'), ('payment', 'Оплата заказа фиатом'), ('payment_bonus', 'Оплата внутренней покупки бонусами'), ('payment_mixed', 'Оплата заказа/покупки бонусами + фиатом'), ('refund', 'Возврат средств'), ('freeze', 'Заморозка средств (оплата исполнителю)'), ('unfreeze', 'Разморозка средств (исполнитель получает оплату)'), ('penalty', 'Штраф (списание средств)'), ('compensation', 'Компенсация (начисление средств)'), ('fiat_transfer', 'Перевод фиата между пользователями')], max_length=155, verbose_name='Тип'),
        ),
    ]
