# Generated by Django 5.0.3 on 2025-02-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_transaction_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Транзакция', 'verbose_name_plural': 'Транзакции'},
        ),
        migrations.AddField(
            model_name='transaction',
            name='dsc',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Дополнение'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='comment_user',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий пользователя'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='comment_whores',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий шлюза'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='number_credit_card',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер кредитной карты'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('bonus_add', 'Пополнение бонусов'), ('bonus_transfer', 'Перевод бонусов'), ('deposit', 'Пополнение фиата'), ('withdrawal', 'Вывод фиата'), ('payment', 'Оплата заказа фиатом'), ('payment_bonus', 'Оплата внутренней покупки бонусами'), ('payment_mixed', 'Оплата заказа/покупки бонусами + фиатом'), ('refund', 'Возврат средств'), ('freeze', 'Заморозка средств'), ('unfreeze', 'Разморозка средств'), ('penalty', 'Штраф (списание средств)'), ('compensation', 'Компенсация (начисление средств)'), ('fiat_transfer', 'Перевод фиата между пользователями')], max_length=155, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'В обработке'), ('completed', 'Завершена'), ('cancelled', 'Отклонена'), ('cancelled_whores', 'Отклонена платежным шлюзом')], default='pending', max_length=40, verbose_name='Статус заявки'),
        ),
    ]
