# Generated by Django 5.0.3 on 2025-02-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_transaction_options_transaction_dsc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='number_credit_card',
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='card_number',
            field=models.CharField(max_length=255, verbose_name='Номер кредитной карты'),
        ),
    ]
