# Generated by Django 5.0.3 on 2025-02-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_remove_withdrawalrequest_number_credit_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='card_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер кредитной карты'),
        ),
    ]
