# Generated by Django 5.1.4 on 2025-02-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('public', 'Публичный'), ('personal', 'Персональный')], default='personal', max_length=30, verbose_name='Тип заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('under_review', 'На рассмотрении'), ('not_accepted_executor', 'Не принят исполнителем'), ('not_accepted_customer', 'Не принят заказчиком'), ('in_progress', 'В работе'), ('sent_for_revision', 'Отправлен на доработку'), ('guaranteed_flight', 'Гарантированный переиод'), ('completed', 'Завершен'), ('rejected_executor', 'Отклонен исполнителем'), ('rejected_customer', 'Отклонен заказчиком')], default='на согласовании', max_length=30, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='type_order',
            field=models.CharField(choices=[('lecture', 'Лекция'), ('practical', 'Практика'), ('lab_work', 'Лабораторная'), ('coursework', 'Курсовая'), ('thesis', 'Диплом'), ('other', 'Другое')], max_length=40, verbose_name='Тип заказа'),
        ),
    ]
