# Generated by Django 5.1.4 on 2025-02-24 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_type_alter_order_status_alter_order_type_order'),
        ('server', '0005_remove_orderstatuslog_order_delete_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='server.discipline', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='order.executordiscipline', verbose_name='Дисциплина'),
        ),
    ]
