# Generated by Django 5.1.4 on 2025-02-24 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_is_urgently_alter_orderstatuslog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('under_review', 'На рассмотрении'), ('changing_conditions', 'Изменение условий'), ('not_accepted_executor', 'Не принят исполнителем'), ('accepted_executor', 'Принят исполнителем'), ('accepted_customer', 'Принят заказчиком'), ('not_accepted_customer', 'Не принят заказчиком'), ('in_progress', 'В работе'), ('sent_for_revision', 'Отправлен на доработку'), ('guaranteed_flight', 'Гарантированный переиод'), ('completed', 'Завершен'), ('rejected_executor', 'Отклонен исполнителем'), ('rejected_customer', 'Отклонен заказчиком')], default='under_review', max_length=30, verbose_name='Статус заказа'),
        ),
        migrations.CreateModel(
            name='OrderAdditionComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('file', models.FileField(blank=True, null=True, upload_to='order/additionComment/%Y/%m/%d/', verbose_name='Файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Дополнение к заказу',
                'verbose_name_plural': 'Дополнения к заказам',
            },
        ),
    ]
