# Generated by Django 5.1.4 on 2025-03-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_status_orderadditioncomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatuslog',
            name='status',
            field=models.CharField(choices=[('under_review', 'На рассмотрении'), ('changing_conditions', 'Изменение условий'), ('not_accepted_executor', 'Не принят исполнителем'), ('not_accepted_customer', 'Не принят заказчиком'), ('accepted_executor', 'Принят исполнителем'), ('accepted_customer', 'Принят заказчиком'), ('in_progress', 'В работе'), ('sent_for_revision', 'Отправлен на доработку'), ('guaranteed_flight', 'Гарантированный переиод'), ('completed', 'Завершен'), ('rejected_executor', 'Отклонен исполнителем'), ('rejected_customer', 'Отклонен заказчиком')], max_length=50, verbose_name='Статус'),
        ),
    ]
