# Generated by Django 5.0.3 on 2025-02-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('заказчик', 'Заказчик'), ('исполнитель', 'Исполнитель'), ('проверяющий', 'Проверяющий'), ('администратор', 'Администратор'), ('finance', 'Финансист')], default='администратор', max_length=20, verbose_name='Роль пользователя'),
        ),
    ]
