# Generated by Django 5.1.4 on 2025-02-23 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_alter_profile_rank_remove_rankdescription_rank_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderstatuslog',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderStatusLog',
        ),
    ]
