# Generated by Django 5.1.4 on 2025-03-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_remove_orderstatuslog_order_delete_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='course',
            field=models.IntegerField(default=1, verbose_name='Курс обучения'),
        ),
        migrations.AlterField(
            model_name='studentcard',
            name='status',
            field=models.CharField(choices=[('На проверке', 'На проверке'), ('Повторная проверка', 'Повторная проверка'), ('Отклонена верификация по СБ', 'Отклонена верификация по СБ'), ('Отклонена анкета исполнителя', 'Отклонена анкета исполнителя'), ('Отправлен на доработку', 'Отправлен на доработку'), ('Принят', 'Принят')], default='На проверке', max_length=60, verbose_name='Статус верификации'),
        ),
    ]
