# Generated by Django 5.1.4 on 2025-03-04 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_profile_course_alter_studentcard_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcard',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='server.profile', verbose_name='Профиль'),
        ),
    ]
