# Generated by Django 5.1.4 on 2025-03-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_alter_studentcard_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_start_auth',
            field=models.BooleanField(default=False, verbose_name='Авторизировался?'),
        ),
    ]
