# Generated by Django 5.1.4 on 2025-03-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_user_is_start_auth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_start_auth',
        ),
        migrations.AddField(
            model_name='user',
            name='count_auth',
            field=models.IntegerField(default=0, verbose_name='Кол-во авторизаций'),
        ),
    ]
